resources:
  jobs:
    deployment:
      name: ${bundle.name}-workflow
      schedule:
        quartz_cron_expression: "0 0 6 ? * MON"
        timezone_id: "Europe/Amsterdam"
        pause_status: ${var.schedule_pause_status}
      tags:
        project_name: "marvel-characters"

      environments:
        - environment_key: default
          spec:
            client: "3"
            dependencies:
              - ../dist/*.whl

      tasks:
        - task_key: "preprocessing"
          environment_key: default
          python_wheel_task:
            package_name: marvel-characters
            entry_point: process-data
            parameters:
              - "--root_path"
              - "${workspace.root_path}"
              - "--env"
              - "${bundle.target}"

        - task_key: "train_model"
          environment_key: default
          depends_on:
            - task_key: "preprocessing"
          python_wheel_task:
            package_name: marvel-characters
            entry_point: train-register-custom-model
            parameters:
              - "--root_path"
              - "${workspace.root_path}"
              - "--env"
              - "${bundle.target}"
              - "--git_sha"
              - "${var.git_sha}"
              - "--job_run_id"
              - "{{job.run_id}}"
              - "--branch"
              - "${var.branch}"

        - task_key: model_updated
          condition_task:
            op: "EQUAL_TO"
            left: "{{tasks.train_model.values.model_updated}}"
            right: "1"
          depends_on:
            - task_key: "train_model"

        - task_key: "deploy_model"
          environment_key: default
          depends_on:
            - task_key: "model_updated"
              outcome: "true"
          python_wheel_task:
            package_name: marvel-characters
            entry_point: deploy-model
            parameters:
              - "--root_path"
              - "${workspace.root_path}"
              - "--env"
              - "${bundle.target}"
